--- #YAML:1.0
name:               Wx-TreeListCtrl
version:            0.13
abstract:           interface to the Wx::TreeListCtrl class
author:
    - Mark Wardell <mwardell@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    Wx::build::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Wx:  0.57
resources:
    keywords:
        - tree
        - data control
        - GUI
        - wx
    repository:  https://wxperltreelistctrl.googlecode.com/svn/trunk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
